/***
1 cliente React con una pagina web que consume via http 1 API MS golang "api-my-insta"
la api MS golang tiene una base de datos relacional en postgresql "db-my-insta"
la api MS golang tiene un broker de mensajes kafka 
la api MS golang consume un s3 donde sube las imagenes en un bucket llama "bucket-my-insta"
la api MS golang esta dockerizada para correr en EKS

**/
@startuml
!define COMPONENT component
!define DATABASE database
!define NODE node

NODE "Cliente" as Client {
  COMPONENT "Cliente React" as ReactClient
}

NODE "Servidor" as Server {
  COMPONENT "API Microservicio Golang" as APIMicroservice
  DATABASE "Base de Datos PostgreSQL" as PostgreSQL
  COMPONENT "Broker de Mensajes Kafka" as KafkaBroker
  COMPONENT "Almacenamiento S3" as S3Storage
}

ReactClient --> APIMicroservice : Consume API via HTTP
APIMicroservice --> PostgreSQL : Acceso a Datos
APIMicroservice --> KafkaBroker : Publica/Consume Mensajes
APIMicroservice --> S3Storage : Sube/Accede Imágenes
@enduml
